"""Checklist-derived data and training blueprints."""

from __future__ import annotations

from pathlib import Path
import json


INTERNAL_DATASETS = [
    "failed_proofs",
    "raven_critiques",
    "counterexamples",
    "forge_experiments",
    "lean_attempts",
    "proof_repairs",
    "attack_maps",
    "routing_logs",
]


ARCHITECTURE_TRAINING_TARGETS = [
    {
        "agent": "core",
        "name": "Mystic-Core",
        "division": "Core",
        "model": "qwen3-14b",
        "adapter": None,
        "implementation_priority": 1,
        "current_stage": "planning_only",
        "datasets": [
            "Internal Mystic Data",
            "NuminaMath-CoT",
            "OpenMathInstruct-2",
            "OpenThoughts3 / OpenThoughts2",
            "OpenR1 / Mixture-of-Thoughts",
            "FLAN Collection",
            "Tulu 3 Datasets",
            "CoT Collection",
            "ToolBench",
            "AgentBench",
            "StackExchange Dumps",
            "Wikipedia / Wikidata",
        ],
        "training_plan": "Train the router and orchestration policy from routing logs, attack maps, math/science instruction traces, and explicit tool-routing examples. Keep the model role separate even when it shares the same provider as other agents.",
    },
    {
        "agent": "prime",
        "name": "Mystic-Prime",
        "division": "Pure Math",
        "model": "deepseek-r1-distill-14b",
        "adapter": "prime_lora_v0",
        "implementation_priority": 2,
        "current_stage": "planning_only",
        "datasets": [
            "Internal Mystic Data",
            "NuminaMath-CoT",
            "OpenMathInstruct-2",
            "OpenMathInstruct-1",
            "OpenThoughts3 / OpenThoughts2",
            "OpenR1 / Mixture-of-Thoughts",
            "AM-DeepSeek-R1-Distilled",
            "OpenWebMath",
            "Nemotron-CC-Math",
            "MegaMath",
            "DeepSeekMath-style Corpus",
            "MetaMathQA",
            "MathInstruct / MAmmoTH",
            "MATH / MATH-500",
            "HARP",
            "OlympiadBench",
            "Omni-MATH",
            "PRM800K",
            "Math-Shepherd Data",
        ],
        "training_plan": "Start with Raven-corrected number-theory traces and verified solution chains, then expand to olympiad-style proof search and process-supervision math corpora.",
    },
    {
        "agent": "algebra",
        "name": "Mystic-Algebra",
        "division": "Pure Math",
        "model": "qwen3-14b",
        "adapter": "algebra_lora_v0",
        "implementation_priority": 2,
        "current_stage": "unconfigured",
        "datasets": [
            "NuminaMath-CoT",
            "OpenMathInstruct-2",
            "OpenMathInstruct-1",
            "OpenThoughts3 / OpenThoughts2",
            "OpenR1 / Mixture-of-Thoughts",
            "OpenWebMath",
            "MegaMath",
            "FineMath",
            "MetaMathQA",
            "MathInstruct / MAmmoTH",
            "MATH / MATH-500",
            "PRM800K",
            "Math-Shepherd Data",
        ],
        "training_plan": "Specialize on symbolic manipulation, equation solving, and proof-structured algebra explanations. Build a dedicated adapter path even if the base model matches Prime.",
    },
    {
        "agent": "geo",
        "name": "Mystic-Geo",
        "division": "Pure Math",
        "model": "qwen3-14b",
        "adapter": "geo_lora_v0",
        "implementation_priority": 2,
        "current_stage": "unconfigured",
        "datasets": [
            "NuminaMath-CoT",
            "OpenMathInstruct-2",
            "OpenWebMath",
            "MATH / MATH-500",
            "HARP",
            "OlympiadBench",
            "Omni-MATH",
            "AlphaGeometry Synthetic Geometry Data",
            "PRM800K",
            "Math-Shepherd Data",
        ],
        "training_plan": "Use geometry-heavy olympiad data plus synthetic theorem corpora to separate diagram-free reasoning, construction steps, and invariant-based proof critique.",
    },
    {
        "agent": "analysis",
        "name": "Mystic-Analysis",
        "division": "Pure Math",
        "model": "qwen3-14b",
        "adapter": "analysis_lora_v0",
        "implementation_priority": 2,
        "current_stage": "unconfigured",
        "datasets": [
            "NuminaMath-CoT",
            "OpenMathInstruct-2",
            "OpenR1 / Mixture-of-Thoughts",
            "OpenWebMath",
            "FineMath",
            "DeepSeekMath-style Corpus",
            "MathInstruct / MAmmoTH",
            "MATH / MATH-500",
            "OlympiadBench",
            "PRM800K",
            "Math-Shepherd Data",
        ],
        "training_plan": "Focus on epsilon-delta arguments, convergence, inequalities, and functional estimates with strong process-supervision to reduce bluffing.",
    },
    {
        "agent": "probability",
        "name": "Mystic-Probability",
        "division": "Pure Math",
        "model": "qwen3-14b",
        "adapter": "probability_lora_v0",
        "implementation_priority": 2,
        "current_stage": "unconfigured",
        "datasets": [
            "NuminaMath-CoT",
            "OpenMathInstruct-2",
            "OpenThoughts3 / OpenThoughts2",
            "MegaMath",
            "MathInstruct / MAmmoTH",
            "MATH / MATH-500",
            "PRM800K",
            "Math-Shepherd Data",
            "GSM8K",
            "AQUA-RAT",
        ],
        "training_plan": "Prioritize combinatorics, expectation, conditioning, and distribution reasoning with step-level correctness labels and conservative uncertainty handling.",
    },
    {
        "agent": "logic",
        "name": "Mystic-Logic",
        "division": "Pure Math",
        "model": "qwen3-14b",
        "adapter": "logic_lora_v0",
        "implementation_priority": 2,
        "current_stage": "unconfigured",
        "datasets": [
            "LeanDojo",
            "LEAN-GitHub",
            "ProofNet",
            "NaturalProofs",
            "miniF2F",
            "PutnamBench",
            "HolStep",
            "CoqGym",
            "Isabelle AFP Dataset",
            "DeepSeek-Prover Data",
        ],
        "training_plan": "Separate informal logical reasoning from formal proof-state navigation. Use theorem-proving corpora plus natural proof datasets for contradiction detection and inference hygiene.",
    },
    {
        "agent": "physics",
        "name": "Mystic-Physics",
        "division": "Science",
        "model": "qwen3-14b",
        "adapter": "physics_lora_v0",
        "implementation_priority": 2,
        "current_stage": "planning_only",
        "datasets": [
            "SciCode",
            "GPQA / GPQA Diamond",
            "SciBench",
            "OlympiadBench",
            "ScienceQA",
            "ARC-Challenge",
            "arXiv source / LaTeX subset",
            "S2ORC",
            "StackExchange Dumps",
        ],
        "training_plan": "Train for mathematically grounded physics derivations, dimensional checks, and scientific coding traces before adding experiment or lab-heavy data.",
    },
    {
        "agent": "complexity",
        "name": "Mystic-Complexity",
        "division": "Science",
        "model": "qwen3-14b",
        "adapter": "complexity_lora_v0",
        "implementation_priority": 2,
        "current_stage": "unconfigured",
        "datasets": [
            "OpenCodeInstruct",
            "CodeContests",
            "APPS",
            "TACO",
            "SWE-bench",
            "SWE-bench Verified",
            "Open-SWE-Traces",
            "The Stack v2 Python subset",
            "StackExchange Dumps",
            "arXiv source / LaTeX subset",
        ],
        "training_plan": "Use algorithmic proofs, reductions, adversarial code tasks, and CS reasoning traces to specialize toward complexity-theory style explanation and counterexample search.",
    },
    {
        "agent": "biomath",
        "name": "Mystic-BioMath",
        "division": "Science",
        "model": "qwen3-14b",
        "adapter": "biomath_lora_v0",
        "implementation_priority": 3,
        "current_stage": "planning_only",
        "datasets": [
            "SciCode",
            "GPQA / GPQA Diamond",
            "LAB-Bench",
            "ScienceQA",
            "S2ORC",
            "Semantic Scholar Open Data",
            "StackExchange Dumps",
        ],
        "training_plan": "Focus on quantitatively structured biology tasks, literature-grounded reasoning, and computational workflows rather than open-ended wet-lab generation.",
    },
    {
        "agent": "chem",
        "name": "Mystic-Chem",
        "division": "Science",
        "model": "qwen3-14b",
        "adapter": "chem_lora_v0",
        "implementation_priority": 3,
        "current_stage": "planning_only",
        "datasets": [
            "SciCode",
            "GPQA / GPQA Diamond",
            "SciBench",
            "MSQA / Materials Science QA",
            "ScienceQA",
            "S2ORC",
            "arXiv source / LaTeX subset",
        ],
        "training_plan": "Train for stoichiometric reasoning, symbolic chemistry derivations, and computational chemistry coding traces before broad chemistry QA expansion.",
    },
    {
        "agent": "lean",
        "name": "Mystic-Lean",
        "division": "Verification",
        "model": "qwen3-14b",
        "adapter": "lean_lora_v0",
        "implementation_priority": 2,
        "current_stage": "planning_only",
        "datasets": [
            "LeanDojo",
            "LEAN-GitHub",
            "ProofNet",
            "miniF2F",
            "PutnamBench",
            "Proof-Pile / Proof-Pile-2",
            "The Stack v2 Lean subset",
            "DeepSeek-Prover Data",
            "Internal Mystic Data",
        ],
        "training_plan": "Start with proof states, tactic prediction, and error repair. Use internal Lean attempts as failure-driven fine-tuning data after the first formal runner is stable.",
    },
    {
        "agent": "smt",
        "name": "Mystic-SMT",
        "division": "Verification",
        "model": "z3",
        "adapter": None,
        "implementation_priority": 3,
        "current_stage": "tool_only",
        "datasets": [
            "ToolBench",
            "Gorilla / APIBench",
            "AgentBench",
            "APPS",
            "TACO",
            "HumanEval / MBPP / MBPP+",
            "LiveCodeBench",
        ],
        "training_plan": "Treat SMT as a tool-first component. Collect solver calls, satisfiable or unsatisfiable traces, and counterexample logs before considering any auxiliary adapter around solver orchestration.",
    },
    {
        "agent": "raven",
        "name": "Mystic-Raven",
        "division": "Verification",
        "model": "qwen3-14b",
        "adapter": "raven_lora_v0",
        "implementation_priority": 1,
        "current_stage": "active_cycle",
        "datasets": [
            "Internal Mystic Data",
            "NuminaMath-CoT",
            "ProofNet",
            "NaturalProofs",
            "MATH / MATH-500",
            "PRM800K",
            "Math-Shepherd Data",
            "miniF2F",
        ],
        "training_plan": "Use failed proofs, critiques, repair attempts, and step-level correctness labels to train a conservative proof referee. Current real training path is the Qwen 0.5B Raven cycle on Kaggle.",
    },
    {
        "agent": "forge",
        "name": "Mystic-Forge",
        "division": "Discovery",
        "model": "qwen3-coder",
        "adapter": "forge_lora_v0",
        "implementation_priority": 1,
        "current_stage": "planning_only",
        "datasets": [
            "Internal Mystic Data",
            "The Stack v2 Python subset",
            "The Stack v2 Sage/SymPy subset",
            "OpenCodeInstruct",
            "CodeContests",
            "APPS",
            "TACO",
            "Codehacks",
            "SciCode",
            "ToolBench",
            "SWE-bench",
            "Open-SWE-Traces",
        ],
        "training_plan": "Train code-first experiment generation, execution repair, and counterexample search. Internal forge experiments and Python runner logs are the highest-value future data source.",
    },
    {
        "agent": "conjecture",
        "name": "Mystic-Conjecture",
        "division": "Discovery",
        "model": "qwen3-14b",
        "adapter": "conjecture_lora_v0",
        "implementation_priority": 2,
        "current_stage": "unconfigured",
        "datasets": [
            "NuminaMath-CoT",
            "OpenMathInstruct-2",
            "OpenThoughts3 / OpenThoughts2",
            "OpenR1 / Mixture-of-Thoughts",
            "OpenWebMath",
            "MegaMath",
            "MetaMathQA",
            "MATH / MATH-500",
            "HARP",
            "OlympiadBench",
            "StackExchange Dumps",
            "arXiv source / LaTeX subset",
        ],
        "training_plan": "Bias the model toward proposing candidate lemmas, reformulations, and attack directions rather than polished final proofs. Train separately from Prime and Pattern despite shared base models.",
    },
    {
        "agent": "pattern",
        "name": "Mystic-Pattern",
        "division": "Discovery",
        "model": "qwen3-14b",
        "adapter": "pattern_lora_v0",
        "implementation_priority": 2,
        "current_stage": "planning_only",
        "datasets": [
            "Internal Mystic Data",
            "OpenWebMath",
            "MegaMath",
            "DeepSeekMath-style Corpus",
            "MetaMathQA",
            "MATH / MATH-500",
            "PRM800K",
            "Math-Shepherd Data",
            "StackExchange Dumps",
        ],
        "training_plan": "Train on invariants, recurrence behavior, modular patterns, and residue-class observations extracted from internal experiments and math corpora.",
    },
    {
        "agent": "simulator",
        "name": "Mystic-Simulator",
        "division": "Discovery",
        "model": "qwen3-coder",
        "adapter": "simulator_lora_v0",
        "implementation_priority": 3,
        "current_stage": "unconfigured",
        "datasets": [
            "The Stack v2 Python subset",
            "The Stack v2 Sage/SymPy subset",
            "OpenCodeInstruct",
            "SciCode",
            "ToolBench",
            "Gorilla / APIBench",
            "AgentBench",
            "HumanEval / MBPP / MBPP+",
        ],
        "training_plan": "Specialize on writing small numerical or symbolic simulators that support Forge and Raven verification loops. Start with execution stability and I/O discipline, not creativity.",
    },
    {
        "agent": "archive",
        "name": "Mystic-Archive",
        "division": "Memory",
        "model": "database",
        "adapter": None,
        "implementation_priority": 1,
        "current_stage": "tool_only",
        "datasets": [
            "Internal Mystic Data",
            "Wikipedia / Wikidata",
            "StackExchange Dumps",
            "S2ORC",
            "Semantic Scholar Open Data",
        ],
        "training_plan": "Archive is a storage subsystem, not a standalone LoRA target at v0. Use checklist datasets to define schemas, indexing keys, and retrieval policies for future memory-conditioned agents.",
    },
    {
        "agent": "knowledge_graph",
        "name": "Mystic-KnowledgeGraph",
        "division": "Memory",
        "model": "graph_db",
        "adapter": None,
        "implementation_priority": 3,
        "current_stage": "tool_only",
        "datasets": [
            "Wikipedia / Wikidata",
            "Semantic Scholar Open Data",
            "arXiv Metadata + Paper Subset",
            "S2ORC",
        ],
        "training_plan": "Build graph extraction and linking pipelines from structured academic and encyclopedic sources before any graph-aware adapter training.",
    },
    {
        "agent": "evolution",
        "name": "Mystic-Evolution",
        "division": "Memory",
        "model": "dataset_builder",
        "adapter": None,
        "implementation_priority": 3,
        "current_stage": "tool_only",
        "datasets": [
            "Internal Mystic Data",
            "PRM800K",
            "Math-Shepherd Data",
            "ToolBench",
            "Open-SWE-Traces",
        ],
        "training_plan": "Treat Evolution as the data curation layer that scores failures, promotes useful traces, and assembles new train-ready corpora from internal logs and external supervision sets.",
    },
    {
        "agent": "report",
        "name": "Mystic-Report",
        "division": "Report",
        "model": "qwen3-14b",
        "adapter": None,
        "implementation_priority": 1,
        "current_stage": "planning_only",
        "datasets": [
            "Internal Mystic Data",
            "FLAN Collection",
            "Tulu 3 Datasets",
            "CoT Collection",
            "Semantic Scholar Open Data",
            "arXiv Metadata + Paper Subset",
            "StackExchange Dumps",
        ],
        "training_plan": "Train uncertainty-preserving report generation from archived findings, Raven critiques, and experiment summaries. Keep report synthesis separate from Core routing and Raven verification.",
    },
]


TRAINING_TARGETS = [
    {
        "adapter": "raven_lora_v0",
        "agent": "raven",
        "label": "Raven-LoRA",
        "base_model": "qwen3-14b",
        "priority": 1,
        "datasets": ["failed_proofs", "raven_critiques", "proof_repairs"],
    },
    {
        "adapter": "forge_lora_v0",
        "agent": "forge",
        "label": "Forge-LoRA",
        "base_model": "qwen3-coder",
        "priority": 2,
        "datasets": ["forge_experiments", "counterexamples", "OpenCodeInstruct", "SciCode"],
    },
    {
        "adapter": "prime_lora_v0",
        "agent": "prime",
        "label": "Prime-LoRA",
        "base_model": "deepseek-r1-distill-14b",
        "priority": 3,
        "datasets": ["NuminaMath-CoT", "OpenMathInstruct-2", "OpenR1", "raven_critiques"],
    },
    {
        "adapter": "lean_lora_v0",
        "agent": "lean",
        "label": "Lean-LoRA",
        "base_model": "qwen3-14b",
        "priority": 4,
        "datasets": ["LeanDojo", "LEAN-GitHub", "ProofNet", "lean_attempts"],
    },
    {
        "adapter": "core_router_lora_v0",
        "agent": "core",
        "label": "Core-Router-LoRA",
        "base_model": "qwen3-14b",
        "priority": 5,
        "datasets": ["routing_logs", "attack_maps", "Internal Mystic Data"],
    },
    {
        "adapter": "pattern_lora_v0",
        "agent": "pattern",
        "label": "Pattern-LoRA",
        "base_model": "qwen3-14b",
        "priority": 6,
        "datasets": ["counterexamples", "forge_experiments", "OpenWebMath"],
    },
    {
        "adapter": "physics_lora_v0",
        "agent": "physics",
        "label": "Physics-LoRA",
        "base_model": "qwen3-14b",
        "priority": 7,
        "datasets": ["GPQA Diamond", "SciBench", "SciCode"],
    },
    {
        "adapter": "chem_lora_v0",
        "agent": "chem",
        "label": "Chem-LoRA",
        "base_model": "qwen3-14b",
        "priority": 8,
        "datasets": ["GPQA Diamond", "SciCode", "MSQA"],
    },
    {
        "adapter": "biomath_lora_v0",
        "agent": "biomath",
        "label": "BioMath-LoRA",
        "base_model": "qwen3-14b",
        "priority": 9,
        "datasets": ["LAB-Bench", "GPQA Diamond", "SciCode"],
    },
    {
        "adapter": "report_lora_v0",
        "agent": "report",
        "label": "Report-LoRA",
        "base_model": "qwen3-14b",
        "priority": 10,
        "datasets": ["final_reports", "structured_summaries", "raven_critiques"],
    },
]


CHECKLIST_DATASETS = [
    {"rank": 1, "name": "Internal Mystic Data", "priority": "critical", "data": INTERNAL_DATASETS},
    {"rank": 2, "name": "NuminaMath-CoT", "priority": "critical", "data": ["math problems", "cot solutions"]},
    {"rank": 3, "name": "OpenMathInstruct-2", "priority": "critical", "data": ["math instruction", "problem-solution", "code-interpreter traces"]},
    {"rank": 4, "name": "OpenMathInstruct-1", "priority": "critical", "data": ["problem-solution pairs"]},
    {"rank": 5, "name": "OpenThoughts3 / OpenThoughts2", "priority": "critical", "data": ["math/code/science reasoning traces"]},
    {"rank": 6, "name": "OpenR1 / Mixture-of-Thoughts", "priority": "critical", "data": ["verified reasoning traces"]},
    {"rank": 7, "name": "AM-DeepSeek-R1-Distilled", "priority": "critical", "data": ["distilled reasoning traces"]},
    {"rank": 8, "name": "LeanDojo", "priority": "critical", "data": ["Lean proof states", "tactics", "premises"]},
    {"rank": 9, "name": "LEAN-GitHub", "priority": "critical", "data": ["Lean theorem and tactic corpus"]},
    {"rank": 10, "name": "ProofNet", "priority": "high", "data": ["natural language proof", "Lean statement"]},
    {"rank": 11, "name": "miniF2F", "priority": "high", "data": ["formal olympiad theorem proving"]},
    {"rank": 12, "name": "PutnamBench", "priority": "high", "data": ["formal theorem proving"]},
    {"rank": 13, "name": "Proof-Pile / Proof-Pile-2", "priority": "very_high", "data": ["formal math and theorem corpus"]},
    {"rank": 14, "name": "The Stack v2 Python subset", "priority": "very_high", "data": ["Python source code"]},
    {"rank": 15, "name": "The Stack v2 Lean subset", "priority": "very_high", "data": ["Lean and mathlib code"]},
    {"rank": 16, "name": "The Stack v2 Sage/SymPy subset", "priority": "very_high", "data": ["SageMath and SymPy code"]},
    {"rank": 17, "name": "OpenCodeInstruct", "priority": "very_high", "data": ["code instruction", "tests", "feedback"]},
    {"rank": 18, "name": "CodeContests", "priority": "very_high", "data": ["programming problems", "solutions", "tests"]},
    {"rank": 19, "name": "APPS", "priority": "high", "data": ["coding problems and Python solutions"]},
    {"rank": 20, "name": "TACO", "priority": "high", "data": ["algorithmic code generation and tests"]},
    {"rank": 21, "name": "Codehacks", "priority": "high", "data": ["adversarial tests", "counterexamples"]},
    {"rank": 22, "name": "SciCode", "priority": "critical", "data": ["scientific coding tasks"]},
    {"rank": 23, "name": "OpenWebMath", "priority": "critical", "data": ["math web text", "latex"]},
    {"rank": 24, "name": "Nemotron-CC-Math", "priority": "critical", "data": ["math/science pretraining corpus"]},
    {"rank": 25, "name": "MegaMath", "priority": "very_high", "data": ["math text", "math code", "synthetic qa"]},
    {"rank": 26, "name": "FineMath", "priority": "high", "data": ["filtered math web corpus"]},
    {"rank": 27, "name": "DeepSeekMath-style Corpus", "priority": "critical", "data": ["filtered math web corpus"]},
    {"rank": 28, "name": "MetaMathQA", "priority": "high", "data": ["rephrased math qa"]},
    {"rank": 29, "name": "MathInstruct / MAmmoTH", "priority": "very_high", "data": ["cot and pot math instruction"]},
    {"rank": 30, "name": "MATH / MATH-500", "priority": "high", "data": ["competition math solutions"]},
]


INGESTION_SOURCES = [
    {
        "name": "Internal Mystic Data",
        "slug": "internal_mystic_data",
        "priority": 1,
        "source_type": "local",
        "status": "bootstrap_ready",
        "recommended_target_agents": ["raven", "forge", "prime", "lean", "core", "pattern", "report"],
    },
    {
        "name": "NuminaMath-CoT",
        "slug": "numinamath_cot",
        "priority": 2,
        "source_type": "public_dataset",
        "status": "manifest_ready",
        "hf_search": "NuminaMath-CoT",
        "preferred_repo_id": "AI-MO/NuminaMath-CoT",
        "recommended_target_agents": ["prime", "core", "report"],
    },
    {
        "name": "OpenMathInstruct-2",
        "slug": "openmathinstruct_2",
        "priority": 3,
        "source_type": "public_dataset",
        "status": "manifest_ready",
        "hf_search": "OpenMathInstruct-2",
        "preferred_repo_id": "nvidia/OpenMathInstruct-2",
        "recommended_target_agents": ["prime", "core", "report"],
    },
    {
        "name": "OpenMathInstruct-1",
        "slug": "openmathinstruct_1",
        "priority": 4,
        "source_type": "public_dataset",
        "status": "manifest_ready",
        "hf_search": "OpenMathInstruct-1",
        "preferred_repo_id": "nvidia/OpenMathInstruct-1",
        "recommended_target_agents": ["prime", "core"],
    },
    {
        "name": "OpenThoughts3 / OpenThoughts2",
        "slug": "openthoughts",
        "priority": 5,
        "source_type": "public_dataset",
        "status": "manifest_ready",
        "hf_search": "OpenThoughts",
        "preferred_repo_id": "open-thoughts/OpenThoughts-114k",
        "recommended_target_agents": ["prime", "forge", "core", "report"],
    },
    {
        "name": "OpenR1 / Mixture-of-Thoughts",
        "slug": "openr1_mixture_of_thoughts",
        "priority": 6,
        "source_type": "public_dataset",
        "status": "manifest_ready",
        "hf_search": "OpenR1",
        "preferred_repo_id": "open-r1/OpenR1-Math-220k",
        "recommended_target_agents": ["prime", "core", "lean"],
    },
    {
        "name": "AM-DeepSeek-R1-Distilled",
        "slug": "am_deepseek_r1_distilled",
        "priority": 7,
        "source_type": "public_dataset",
        "status": "manifest_ready",
        "hf_search": "AM-DeepSeek-R1-Distilled",
        "recommended_target_agents": ["prime", "core", "report"],
    },
    {
        "name": "LeanDojo",
        "slug": "leandojo",
        "priority": 8,
        "source_type": "public_dataset",
        "status": "manifest_ready",
        "hf_search": "LeanDojo",
        "preferred_repo_id": "tasksource/leandojo",
        "recommended_target_agents": ["lean"],
    },
    {
        "name": "LEAN-GitHub",
        "slug": "lean_github",
        "priority": 9,
        "source_type": "public_dataset",
        "status": "manifest_ready",
        "hf_search": "LEAN-GitHub",
        "recommended_target_agents": ["lean"],
    },
    {
        "name": "ProofNet",
        "slug": "proofnet",
        "priority": 10,
        "source_type": "public_dataset",
        "status": "manifest_ready",
        "hf_search": "ProofNet",
        "preferred_repo_id": "hoskinson-center/proofnet",
        "recommended_target_agents": ["lean", "raven", "report"],
    },
]


SOFTWARE_STACK = [
    "Python 3.11+",
    "Git",
    "Docker",
    "SQLite",
    "Ollama",
    "Transformers",
    "PEFT",
    "Unsloth",
    "Axolotl",
    "TRL",
    "PyTorch",
    "FastAPI",
    "Typer",
    "SQLAlchemy",
    "Pydantic",
    "pytest",
    "SymPy",
    "NumPy",
    "SciPy",
    "SageMath",
    "Lean 4",
    "Z3",
    "Jupyter",
    "DVC",
    "rclone",
    "Weights & Biases",
    "MLflow",
]


AGENT_DIVISIONS = {
    "core": "core",
    "prime": "pure_math",
    "algebra": "pure_math",
    "geo": "pure_math",
    "analysis": "pure_math",
    "probability": "pure_math",
    "logic": "pure_math",
    "forge": "discovery",
    "conjecture": "discovery",
    "lean": "verification",
    "raven": "verification",
    "pattern": "discovery",
    "simulator": "discovery",
    "physics": "science",
    "complexity": "science",
    "chem": "science",
    "biomath": "science",
    "smt": "verification",
    "archive": "memory",
    "knowledge_graph": "memory",
    "evolution": "memory",
    "report": "report",
}


INTERNAL_RECORD_ROUTING = {
    "failed_proofs": ["raven"],
    "raven_critiques": ["raven", "report", "prime"],
    "counterexamples": ["forge", "pattern"],
    "forge_experiments": ["forge", "pattern"],
    "lean_attempts": ["lean"],
    "proof_repairs": ["raven", "prime"],
    "attack_maps": ["core", "prime"],
    "routing_logs": ["core"],
}


def write_json(path: str | Path, payload: object) -> None:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
