import { lazy, Suspense, useState } from "react";
import { NavLink, Navigate, Route, Routes, useNavigate, useParams } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { api, ApiError } from "./api/client";
import type { Provider } from "./api/contracts";

const LabEditor = lazy(() => import("./components/lab-editor"));
const LabBenchmark = lazy(() => import("./components/lab-benchmark"));
const nav = [["/", "Overview"], ["/mcp", "MCP diagnostics"], ["/providers", "Providers"], ["/research", "Research"], ["/scenes", "Scenes"], ["/activity", "Activity"], ["/settings", "Settings"]] as const;
export function Status({ value }: { value: string | boolean | undefined }) { const text = typeof value === "boolean" ? (value ? "ready" : "not ready") : value ?? "unknown"; return <span className={`status ${/ready|ok|connected|completed|true/.test(text) ? "good" : /error|blocked|offline|false/.test(text) ? "bad" : "warn"}`}>{text}</span>; }
function Shell({ children }: { children: React.ReactNode }) { const session = useQuery({ queryKey: ["session"], queryFn: api.session }); const navigate = useNavigate(); async function logout() { await api.logout(); await session.refetch(); navigate("/"); }
  if (session.isLoading) return <main className="centered">Checking secure console session…</main>;
  if (!session.data?.authenticated) return <Login onDone={() => session.refetch()} />;
  return <div className="shell"><aside><div className="brand">MYSTIC <span>LAB</span></div><p className="eyebrow">CONTROL CENTER</p><nav>{nav.map(([to, label]) => <NavLink key={to} to={to} end={to === "/"}>{label}</NavLink>)}</nav><button className="quiet" onClick={logout}>Sign out</button></aside><main className="content">{children}</main></div>; }
function Login({ onDone }: { onDone: () => void }) { const [token, setToken] = useState(""); const [error, setError] = useState(""); async function submit(event: React.FormEvent) { event.preventDefault(); try { await api.login(token); onDone(); } catch { setError("Login was not accepted."); } }
  return <main className="login"><form onSubmit={submit}><div className="brand">MYSTIC <span>LAB</span></div><h1>Control Center</h1><p>Use the console administrator credential. It is verified only by the secure server.</p><label>Administrator credential<input aria-label="Administrator credential" type="password" autoComplete="current-password" value={token} onChange={(e) => setToken(e.target.value)} /></label>{error && <p role="alert" className="error">{error}</p>}<button>Sign in</button></form></main>; }
function PageHeader({ title, children }: { title: string; children?: React.ReactNode }) { return <header className="page-header"><div><p className="eyebrow">MYSTIC LAB / OPERATIONS</p><h1>{title}</h1></div>{children}</header>; }
function Loading() { return <div className="panel">Loading live Mystic state…</div>; }
function Failure({ error }: { error: unknown }) { return <div className="panel error" role="alert">{error instanceof ApiError ? error.message : "The live service could not be reached."}</div>; }
function Overview() { const status = useQuery({ queryKey: ["status"], queryFn: api.status, refetchInterval: 30_000 }); const health = useQuery({ queryKey: ["health"], queryFn: api.health, refetchInterval: 30_000 }); if (status.isLoading || health.isLoading) return <Loading />; if (status.error || health.error || !status.data || !health.data) return <Failure error={status.error ?? health.error} />; const data = status.data; const healthData = health.data; const tools = (data.tools as Record<string, string> | undefined) ?? {}; const blockers = (data.blockers as string[] | undefined) ?? [];
  return <><PageHeader title="Operations overview"><button onClick={() => { void status.refetch(); void health.refetch(); }}>Refresh live state</button></PageHeader>{blockers.length > 0 && <div className="alert">Operational blockers: {blockers.join(", ")}</div>}<section className="metrics"><Metric label="Worker health" value={String(healthData.status ?? "unknown")} /><Metric label="MCP readiness" value={String(data.mcp_server_status ?? "unknown")} /><Metric label="Tools" value={String(Object.keys(tools).length)} /><Metric label="Storage" value={String(data.storage_backend ?? "unknown")} /><Metric label="Providers" value={String((data.provider_registry as unknown[] | undefined)?.length ?? 0)} /><Metric label="Remote import" value={String(data.chatgpt_remote_import_ready ?? false)} /></section><section className="two-column"><Panel title="Backend status"><KeyValues values={{ "Public endpoint": data.remote_mcp_public_endpoint, "Worker mode": data.runtime_mode, "Storage": data.storage_backend, "Tool count": Object.keys(tools).length }} /></Panel><Panel title="Recent safe errors">{((data.recent_errors as string[] | undefined) ?? []).length ? <ul>{(data.recent_errors as string[]).map((item) => <li key={item}>{item}</li>)}</ul> : <p>No safe errors reported.</p>}</Panel></section><p className="caption">Session, experiment, and scene counts are shown only when the backend exposes a list operation; the console does not invent operational data.</p></>; }
export function Metric({ label, value }: { label: string; value: string }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="panel"><h2>{title}</h2>{children}</section>; }
function KeyValues({ values }: { values: Record<string, unknown> }) { return <dl>{Object.entries(values).map(([key, value]) => <><dt key={`${key}-t`}>{key}</dt><dd key={`${key}-v`}>{String(value ?? "—")}</dd></>)}</dl>; }
function Mcp() { const query = useQuery({ queryKey: ["mcp"], queryFn: api.mcp }); if (query.isLoading) return <Loading />; if (query.error || !query.data) return <Failure error={query.error} />; const data = query.data; return <><PageHeader title="MCP diagnostics" /><section className="two-column"><Panel title="Health probe"><pre>{JSON.stringify(data.health, null, 2)}</pre></Panel><Panel title="Status probe"><pre>{JSON.stringify(data.status, null, 2)}</pre></Panel></section><Panel title={`Visible safe domains (${data.tools.length})`}><div className="chips">{data.tools.map((tool) => <span key={tool.name}>{tool.name}</span>)}</div></Panel></>; }
function Providers() { const query = useQuery({ queryKey: ["providers"], queryFn: api.providers }); if (query.isLoading) return <Loading />; if (query.error || !query.data) return <Failure error={query.error} />; const providers = query.data.providers; return <><PageHeader title="Provider status" /><section className="panel table-wrap"><table><thead><tr><th>Provider</th><th>Auth</th><th>Configured</th><th>Status</th><th>Model</th><th>Last verified</th><th /></tr></thead><tbody>{providers.map((provider) => <ProviderRow key={provider.provider_id} provider={provider} />)}</tbody></table></section></>; }
function ProviderRow({ provider }: { provider: Provider }) { const query = useQuery({ queryKey: ["provider-verify", provider.provider_id], enabled: false, queryFn: () => api.verifyProvider(provider.provider_id) }); return <tr><td><strong>{provider.display_name ?? provider.provider_id}</strong><small>{provider.provider_type ?? "external provider"}</small></td><td>{provider.auth_method ?? "—"}</td><td><Status value={provider.configured} /></td><td><Status value={provider.ready ?? provider.connected} /></td><td>{provider.model_name ?? provider.model_list?.join(", ") ?? "—"}</td><td>{provider.last_verified_at ?? "—"}</td><td><button className="small" onClick={() => void query.refetch()}>{query.isFetching ? "Verifying…" : "Verify"}</button></td></tr>; }
function Research() { const navigate = useNavigate(); const sessions = useQuery({ queryKey: ["research-list"], queryFn: api.research }); const [problem, setProblem] = useState("Verify the Mystic 3D laboratory"); const [message, setMessage] = useState(""); async function create(event: React.FormEvent) { event.preventDefault(); try { const created = await fetch("/api/research", { method: "POST", credentials: "same-origin", headers: { "content-type": "application/json" }, body: JSON.stringify({ problem, domain: "physics", goal: problem, mode: "cheap", participants: ["tool"] }) }).then((r) => r.json() as Promise<{ session_id?: string }>); if (created.session_id) navigate(`/research/${created.session_id}`); else setMessage("The backend did not return a session ID."); } catch { setMessage("Could not create the research session."); } }
 const rows = (sessions.data?.sessions as Array<Record<string, unknown>> | undefined) ?? []; return <><PageHeader title="Research laboratory" /><section className="two-column"><Panel title="Create session"><form className="stack" onSubmit={create}><label>Research goal<textarea value={problem} onChange={(e) => setProblem(e.target.value)} /></label><p className="caption">Creates a live Mystic LAB session with domain <code>physics</code>.</p><button>Create live session</button>{message && <p role="alert" className="error">{message}</p>}</form></Panel><Panel title="Authoritative sessions">{sessions.isLoading ? <Loading /> : <div className="tree">{rows.length ? rows.map((session) => <button key={String(session.session_id)} onClick={() => navigate(`/research/${encodeURIComponent(String(session.session_id))}`)}><strong>{String(session.goal ?? session.session_id)}</strong><small>{String(session.status ?? "unknown")} · {String(session.updated_at ?? "")}</small></button>) : <p className="empty">No live sessions returned by Mystic.</p>}</div>}<OpenById prefix="/research/" label="Open session" /></Panel></section></>; }
function ResearchDetail() { const { sessionId = "" } = useParams(); const query = useQuery({ queryKey: ["research", sessionId], queryFn: () => api.getResearch(sessionId) }); const navigate = useNavigate(); if (query.isLoading) return <Loading />; if (query.error || !query.data) return <Failure error={query.error} />; const session = query.data.session as Record<string, unknown> | undefined; async function createScene() { const title = prompt("Scene title", "Research scene"); if (!title) return; const scene = await api.createScene({ sessionId, title }); navigate(`/lab/${scene.sceneId}`); } return <><PageHeader title="Research workspace"><div className="toolbar-actions"><button onClick={() => void api.advanceResearch(sessionId).then(() => query.refetch())}>Advance session</button><button onClick={() => void api.reportResearch(sessionId).then(() => query.refetch())}>Generate report</button><button onClick={() => void createScene()}>Create linked scene</button></div></PageHeader><section className="two-column"><Panel title="Summary"><KeyValues values={{ "Session": sessionId, "Domain": session?.domain, "Goal": session?.goal, "Phase": session?.current_phase, "Status": session?.status, "Updated": session?.updated_at }} /></Panel><Panel title="Safe research state"><pre>{JSON.stringify(query.data, null, 2)}</pre></Panel></section><Panel title="Workspace tabs"><div className="chips">{["Summary", "Claims", "Experiments", "Simulations", "Failures", "Memory", "Reports", "Scenes", "Activity"].map((tab) => <span key={tab}>{tab}</span>)}</div><p className="caption">Each tab is backed by this session's typed Mystic payload; fields unavailable from the current backend remain absent rather than being fabricated.</p></Panel></>; }
function Scenes() { const navigate = useNavigate(); const scenes = useQuery({ queryKey: ["scene-list"], queryFn: api.scenes }); const [sessionId, setSessionId] = useState(""); const [title, setTitle] = useState("New Mystic scene"); async function create(event: React.FormEvent) { event.preventDefault(); const scene = await api.createScene({ sessionId, title }); navigate(`/lab/${scene.sceneId}`); } const rows = (scenes.data?.scenes as Array<Record<string, unknown>> | undefined) ?? []; return <><PageHeader title="3D scene library" /><section className="two-column"><Panel title="Authoritative scene library">{scenes.isLoading ? <Loading /> : <div className="tree">{rows.length ? rows.map((scene) => <button key={String(scene.scene_id)} onClick={() => navigate(`/lab/${encodeURIComponent(String(scene.scene_id))}`)}><strong>{String(scene.title ?? scene.scene_id)}</strong><small>{String(scene.object_count ?? 0)} objects · rev {String(scene.revision ?? 1)}</small></button>) : <p className="empty">No persisted scenes returned by Mystic.</p>}</div>}<OpenById prefix="/lab/" label="Open 3D laboratory" /></Panel><Panel title="Create linked scene"><form className="stack" onSubmit={(event) => void create(event)}><label>Session ID<input value={sessionId} onChange={(event) => setSessionId(event.target.value)} required /></label><label>Scene title<input value={title} onChange={(event) => setTitle(event.target.value)} required /></label><button>Create authoritative scene</button></form></Panel></section></>; }
function OpenById({ prefix, label }: { prefix: string; label: string }) { const [id, setId] = useState(""); const navigate = useNavigate(); return <form className="inline-form" onSubmit={(e) => { e.preventDefault(); if (id.trim()) navigate(`${prefix}${encodeURIComponent(id.trim())}`); }}><label>ID<input value={id} onChange={(e) => setId(e.target.value)} /></label><button>{label}</button></form>; }
function Activity() { const activity = useQuery({ queryKey: ["activity"], queryFn: api.activity, refetchInterval: 30_000 }); const rows = (activity.data?.events as Array<Record<string, unknown>> | undefined) ?? []; if (activity.isLoading) return <Loading />; if (activity.error) return <Failure error={activity.error} />; return <><PageHeader title="Safe activity stream" /><Panel title="Authoritative audit events">{rows.length ? <ul>{rows.map((event) => <li key={String(event.event_id)}><strong>{String(event.tool_name)}</strong> — {String(event.safe_summary)} <small>{String(event.created_at)}</small></li>)}</ul> : <p>No safe audit events returned by Mystic.</p>}</Panel></>; }
function Settings() { return <><PageHeader title="Console settings" /><Panel title="Deployment and security"><ul><li>Admin credentials are verified server-side.</li><li>Session cookies are Secure, HttpOnly, and SameSite=Strict.</li><li>Provider secrets and backend bearer tokens are never rendered or stored in browser storage.</li><li>Configure Cloudflare Access ahead of the fallback admin login in production.</li></ul></Panel></>; }
export default function App() { return <Shell><Routes><Route path="/" element={<Overview />} /><Route path="/mcp" element={<Mcp />} /><Route path="/providers" element={<Providers />} /><Route path="/research" element={<Research />} /><Route path="/research/:sessionId" element={<ResearchDetail />} /><Route path="/scenes" element={<Scenes />} /><Route path="/lab/benchmark" element={<Suspense fallback={<Loading />}><LabBenchmark /></Suspense>} /><Route path="/lab/:sceneId" element={<Suspense fallback={<Loading />}><LabEditor /></Suspense>} /><Route path="/activity" element={<Activity />} /><Route path="/settings" element={<Settings />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></Shell>; }
