import { useQuery } from "@tanstack/react-query";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { api, ApiError } from "../api/client";
import type { ScientificJobSummary } from "../api/contracts";

function Failure({ error }: { error: unknown }) { return <p className="panel error" role="alert">{error instanceof ApiError ? error.message : "Scientific job data is unavailable."}</p>; }
function timestamp(value: string | undefined) { return value ? new Date(value).toLocaleString() : "—"; }

export function ScientificJobsPage() {
  const navigate=useNavigate(); const [search]=useSearchParams(); const campaignId=search.get("campaign_id") ?? ""; const jobs=useQuery({queryKey:["scientific-jobs",campaignId],queryFn:()=>api.scientificJobs(campaignId || undefined),refetchInterval:10_000}); const stats=useQuery({queryKey:["scientific-job-statistics",campaignId],queryFn:()=>api.scientificJobStatistics(campaignId || undefined),refetchInterval:10_000});
  if (jobs.error) return <Failure error={jobs.error}/>;
  const rows=jobs.data?.jobs ?? []; const deadLetters=rows.filter((job)=>job.status==="DEAD_LETTER" || job.status==="FAILED");
  return <><header className="page-header"><div><p className="eyebrow">MYSTIC LAB / DURABLE EXECUTION</p><h1>Scientific job queue</h1><p>Physical execution may repeat; campaign result application is logically idempotent.{campaignId ? ` Filtered to ${campaignId}.` : ""}</p></div><button onClick={()=>void Promise.all([jobs.refetch(),stats.refetch()])}>Refresh</button></header><section className="metrics"><div className="metric"><span>Ready</span><strong>{String(stats.data?.ready_jobs ?? 0)}</strong></div><div className="metric"><span>Leased</span><strong>{String(stats.data?.leased_jobs ?? 0)}</strong></div><div className="metric"><span>Running</span><strong>{String(stats.data?.running_jobs ?? 0)}</strong></div><div className="metric"><span>Succeeded</span><strong>{String(stats.data?.succeeded_jobs ?? 0)}</strong></div><div className="metric"><span>Dead letter</span><strong>{String(stats.data?.dead_letter_jobs ?? 0)}</strong></div></section><JobTable title="Job queue" rows={rows} onOpen={(job)=>navigate(`/jobs/${encodeURIComponent(job.job_id)}`)}/><JobTable title="Dead-letter / failure archive" rows={deadLetters} onOpen={(job)=>navigate(`/jobs/${encodeURIComponent(job.job_id)}`)} empty="No terminal or retryable failures."/><section className="panel"><h2>Runtime statistics</h2><pre>{JSON.stringify(stats.data ?? {},null,2)}</pre></section></>;
}

function JobTable({ title, rows, onOpen, empty="No durable scientific jobs." }: { title: string; rows: ScientificJobSummary[]; onOpen: (job: ScientificJobSummary) => void; empty?: string }) {
  return <section className="panel"><h2>{title}</h2>{rows.length ? <div className="tree">{rows.map((job)=><button key={job.job_id} onClick={()=>onOpen(job)}><strong>{job.engine_name} <code>{job.job_id}</code></strong><small>{job.status} · attempt {job.attempt}/{job.max_attempts} · campaign {job.campaign_id} · {timestamp(job.finished_at || job.started_at || job.created_at)}</small></button>)}</div> : <p className="empty">{empty}</p>}</section>;
}

export function ScientificJobDetailPage() {
  const { jobId="" }=useParams(); const job=useQuery({queryKey:["scientific-job",jobId],queryFn:()=>api.scientificJob(jobId),refetchInterval:10_000});
  if (job.isLoading) return <p className="panel">Loading durable scientific job…</p>;
  if (job.error || !job.data) return <Failure error={job.error}/>;
  const data=job.data; const canCancel=["PENDING","READY","LEASED","RUNNING","RETRY_WAIT","FAILED"].includes(data.status); const canRetry=data.status==="FAILED";
  async function control(action:"cancel"|"retry") { try { if (action==="cancel") await api.cancelScientificJob(data.job_id); else await api.retryScientificJob(data.job_id); await job.refetch(); } catch { await job.refetch(); } }
  return <><header className="page-header"><div><p className="eyebrow">SCIENTIFIC JOB / {data.job_id}</p><h1>{data.engine_name} <small>{data.engine_version}</small></h1><p>{data.status} · attempt {data.attempt}/{data.max_attempts} · revision {data.revision}</p></div><div className="toolbar-actions"><button disabled={!canRetry} onClick={()=>void control("retry")}>Retry</button><button className="danger" disabled={!canCancel} onClick={()=>void control("cancel")}>Cancel</button><Link className="button" to={`/campaigns/${encodeURIComponent(data.campaign_id)}`}>Campaign</Link><Link className="button" to="/jobs">Job queue</Link></div></header><section className="two-column"><section className="panel"><h2>Execution and lease</h2><dl><dt>Created</dt><dd>{timestamp(data.created_at)}</dd><dt>Started</dt><dd>{timestamp(data.started_at)}</dd><dt>Completed</dt><dd>{timestamp(data.finished_at)}</dd><dt>Ready at</dt><dd>{timestamp(data.ready_at)}</dd><dt>Lease owner</dt><dd>{String(data.lease_owner || "—")}</dd><dt>Lease expiry</dt><dd>{timestamp(data.lease_expires_at)}</dd><dt>Cancellation</dt><dd>{String((data.lease as Record<string, unknown> | undefined)?.cancellation_requested ?? false)}</dd></dl></section><section className="panel"><h2>Provenance</h2><pre>{JSON.stringify({input_metadata:data.input_metadata,result_metadata:data.result_metadata,provenance:data.provenance,attachment:data.attachment},null,2)}</pre></section></section><section className="panel"><h2>Failure / retry</h2>{data.error || data.attachment_error || data.failure_attachment_error ? <pre>{JSON.stringify({failure_class:data.failure_class,error:data.error,attachment_error:data.attachment_error,failure:data.failure,failure_attachment_state:data.failure_attachment_state,failure_attachment_error:data.failure_attachment_error},null,2)}</pre> : <p className="empty">No accepted failure record.</p>}</section><section className="panel"><h2>Lease history</h2><pre>{JSON.stringify(data.lease_history ?? [],null,2)}</pre></section><section className="panel"><h2>Dispatch outbox</h2><pre>{JSON.stringify(data.outbox ?? [],null,2)}</pre></section><section className="panel"><h2>Audit timeline</h2><pre>{JSON.stringify(data.events ?? [],null,2)}</pre></section></>;
}
